### ISSUE TITLE
can't copy 'htrc/.htrc.default': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by gupta-apoorva** [htrc/HTRC-WorksetToolkit#25]
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1n25qdu7/htrc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5vlhrr5g-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-1n25qdu7/htrc/

**Comment by organisciak** [comment]
I'm getting the same error. @JaimieMurdock?

My workaround was to clone this repository, remove the `.htrc.default` line from `setup.py`, and run `python setup.py install`.

**Comment by organisciak** [comment]
Scratch that, it installed, but it looks like the library wants that file.

**Comment by JaimieMurdock** [comment]
Should be fixed today
